[package]
name = "gitnu"
version = "0.4.6"
authors = ["Nguyen Vu Khang <brew4k@gmail.com>"]
description = """
gitnu indexes your git status so you can use numbers instead of filenames.
"""
homepage = "https://github.com/nguyenvukhang/gitnu"
repository = "https://github.com/nguyenvukhang/gitnu"
documentation = "https://github.com/nguyenvukhang/gitnu"
keywords = ["git"]
categories = ["command-line-utilities"]
license = "MIT"
autotests = false
edition = "2021"

[dependencies]
atty = "0.2.14"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "bench"
path = "bench/main.rs"
harness = false

[lib]
path = "core/lib.rs"
doctest = false

[[bin]]
bench = false
test = false
path = "core/main.rs"
name = "gitnu"

[[test]]
name = "integration"
path = "tests/main.rs"
