[package]
name = "gitnu"
version = "0.3.1"
authors = ["Nguyen Vu Khang <brew4k@gmail.com>"]
description = """
gitnu indexes your git status so you can use numbers instead of filenames.
"""
homepage = "https://github.com/nguyenvukhang/gitnu"
repository = "https://github.com/nguyenvukhang/gitnu"
documentation = "https://github.com/nguyenvukhang/gitnu"
keywords = ["git"]
categories = ["command-line-utilities"]
license = "MIT"
edition = "2021"

[lib]
name = "gitnu_lib"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "gitnu"
path = "src/bin.rs"
test = false
